name: API Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN_SECRET: ${{ secrets.MY_GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create config.properties from secret
        run: |
          mkdir -p src/test/resources/schemas
          cat > src/test/resources/schemas/config.properties <<EOF
          # generated in workflow - do not commit
          base.url.github=https://api.github.com
          github.token=${{ secrets.MY_GH_PAT }}
          github.token.ttlSeconds=3
          EOF

      - name: Run Maven tests
        run: mvn clean test -DsuiteXmlFile=testng.xml

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/**

